### PR TITLE
Make workspace warping completely directionally symmetric

### PR DESCRIPTION
**Pull request by gwhitney**
A priori, there is no reason why the workspace warping functionality should
  treat the horizontal and vertical directions at all differently. Even if
  traditionally horizontal warping was more common, for some in recent times
  as aspect ratios tend to become larger, stacking virtual workspaces
  vertically may make more sense. Similarly, some might want to traverse
  an array of workspaces in column-major, rather than row-major, order.

  Prior to this commit, there were extra parameters for vertical warping (a
  controlling flag and an offset for how many workspaces to jump) as opposed
  to horizontal warping. Also it was impossible to allow vertical warping while
  disallowing vertical warping.

  This commit makes all of the parameters and behavior for horizontal and
  vertical warping equivalent. For backwards compatibility, there is an
  overarching flag controlling whether warping occurs at all, as well as a
  separate control flag and offset for each of horizontal and vertical warping.

### CODE REVIEW

**Comment by mark-t** [comment]
It's hard to argue with that. Unfortunately, I broke my operating system
and decided I should switch to something I have time to maintain properly,
but I haven't even figured out how to start X on boot without a display
manager, much less run fluxbox from source, so could somebody else please
test this and merge it?

  Thanks,
     Mark

P.S. Thanks for MoMath! I hear it's excellent, but it's a little far from
San Diego....

**Comment by gwhitney** [comment]
Thanks for the kind words and for the sentiment that this should be
tested and merged. Incidentally, I do hope to open a different sort of
math visitor center called "Studio Infinity" in the LA area at some
point (obviously not happening in the near future).
   Cheers, Glen

**Comment by mark-t** [comment]
I finally got my act together and tested this. Apparently I'm the only one
around here. It does what it says. It does not quite create a torus, which
is what I would expect, but I guess we didn't do that before either.
Anyway, I've committed this to master now.

  Thanks,
     Mark

**Comment by gwhitney** [comment]
Thanks, Mark, much appreciated. I still have not seen any other window manager with the easy generic tabbing (which it totally seems to me should be in the WM, not implemented separately and idiosyncratically or perhaps not at all in each separate client application) that fluxbox has, which is why I still use it when clearly other WMs have become much more popular. In particular, this way I can get tabs along the left sides of my windows, where they belong because vertical space is more precious than horizontal space on modern screen. No way to do that with internal Firefox tabs! Cheers, Glen

**Comment by gwhitney** [comment]
Not sure where else to put this comment, or whether it will get to anyone relevant: Although this github repository claims to be a mirror (I gather of http://git.fluxbox.org/fluxbox.git/), it does not seem to be keeping up to date; the last commit here as I write this is dated 2020 April 26, whereas at gt.fluxbox.org, there are several commits from 2021 July. My suggestions: either make sure the mirroring is active and automatic, or delete this repository and make the "real" one easy to find from fluxbox.org, or clearly label this repository as potentially stale and provide in its README a link to the "real" one. In a similar vein, the pull requests recently merged into the mainline have not been marked as closed. Thanks for considering.

**Comment by mark-t** [comment]
Yeah, I don't actually know where the github repository came from or who
maintains it. Mathias recently proposed moving the official repository to
github, so this may take care of itself.

**Comment by mgumz** [comment]
The GH repo was claimed by @paultag iirc.

When I sync/push to git.fluxbox.org, I also push to GH. Thats how I keep them in sync. 

And yeah, one idea is to actually move all the hosting over to GH, also for the webpage.

**Comment by paultag** [comment]
@mgumz this is true! I'm happy to do whatever needs done to help! I'm still around just not as much! :+1:

**Comment by gwhitney** [comment]
This is merged, and the github mirror is back up to date, so closing.

**Pull request closed without merging**
