### PR TITLE
Update Translation.m

### PR DESCRIPTION
**Pull request by rodrigo-x**
I´m a brazilian and I think that the translation to pt-br would be better

### CODE REVIEW

**Review by tauil — APPROVED** [review]
Looks good to me!

**Comment by mgumz** [comment]
Thanks for the effort: I'll merge with `master` asap

**Comment by rodrigo-x** [comment]
Thank u guys!

**Comment by mgumz** [comment]
quick question: https://github.com/fluxbox/fluxbox/pull/64 - is PR65 an extension to PR64?

**Comment by mgumz** [comment]
@rodrigo-x ping … is #65 an extension to #64?

**Comment by rodrigo-x** [comment]
@mgumz i think no

**Pull request merged**
