### PR TITLE
StrictMouseFocus fix (#1012)

### PR DESCRIPTION
**Pull request by syrkuit**
This fixes http://sourceforge.net/p/fluxbox/bugs/1012/

### CODE REVIEW

**Comment by mgumz** [comment]
please rephrase the commit-subject to be shorter and more compact.

**Comment by cnkalt** [comment]
Done.

**Comment by luebking** [comment]
Critique of the approach https://sourceforge.net/p/fluxbox/bugs/1012/#f381
Superseded by https://github.com/fluxbox/fluxbox/commit/abd5c9e478ac99f457a1df6292729b615f58bbda
=> PR is pointless/irrelevant to the present codebase.

**Comment by mgumz** [comment]
@syrkuit so, thanks for the effort anyways.

**Pull request closed without merging**
