### PR TITLE
Rebase: Ordered systray for fluxbox (#7)

### PR DESCRIPTION
**Pull request by jansucan**
The systray ordering from the old inactive pull request #7 is a useful feature. I rebased the implementation on the master branch, so it can be merged.

### CODE REVIEW

**Comment by bosim** [comment]
Looks great, I miss this feature as well.
Maybe the new settings should be documented in the fluxbox(1) man page.

**Comment by jansucan** [comment]
> Maybe the new settings should be documented in the fluxbox(1) man page.

Good point. I'm going to add it there.

**Comment by mgumz** [comment]
@jansucan: please add it to the asciidoc file https://github.com/fluxbox/fluxbox/blob/master/doc/asciidoc/fluxbox.txt … from there we create the rest

**Comment by jansucan** [comment]
I will do that. However, I would like to ask you about the asciidoc. I'm not sure if I understand it correctly. Should new information be added only to the asciidoc or to both asciidoc and manpages .in files? If the first option is true, why are the manpages .in files versioned?

**Comment by mgumz** [comment]
having the manpages (allthough a build-artifact) being under version control simplifies things. the asciidoc -> manpage pipeline can be a bit "bigger".

**Comment by jansucan** [comment]
I have noticed that when I rebuilt all the manpages, some of them produced a different output (fbrun, fluxbox-apps, fluxbox-keys, fluxbox-menu, fluxbox). The .in files and the .txt files got out of sync. Should I sync them in a different pull request?

**Comment by mgumz** [comment]
yeah, would be great. upon release-time its the latest that sync will be done … does not hurt to do it before that

**Comment by mgumz** [comment]
merged. thanks!

**Pull request closed without merging**
