### PR TITLE
Fix ArrangeWindows placing/resizing windows incorrectly

### PR DESCRIPTION
**Pull request by Nephiel**
The ArrangeWindows commands did not account for window border width nor space left after arranging, so windows could end up incorrectly placed or not filling all available screen space. These commits should fix that.

### CODE REVIEW

**Comment by mgumz** [comment]
i would like to merge your fix. but your commit-messages are so .. anonym: <Nephiel@users.noreply.github.com>

can you fix this?

i would also like to squash the "borderwidth"-fixes into one.

**Comment by Nephiel** [comment]
Well, I don't see why that would need fixing, but it's done anyway (unchecked "keep email address private" in github profile settings).
Feel free to squash and merge as you like.

**Comment by mgumz** [comment]
"we" dont take commits from "santaclaus" either :)

**Comment by Nephiel** [comment]
So, do I need to do anything else?

**Comment by mgumz** [comment]
nope. just sit back and relax. as soon as i will have access to a machine will merge

**Comment by mgumz** [comment]
`nope. just sit back and relax. as soon as i will have access to a machine will merge`: lame excuse of the year: i was at vacation at that time and things went pretty busy afterwards. thus: i just forgot to look here.

**Comment by Nephiel** [comment]
I can, but won't be able to for the next day or so.
Re: props: no worries, I'm just happy to help.

**Comment by mgumz** [comment]
i will wait... it's not that we are in a hurry or something like that.

**Comment by Nephiel** [comment]
OK, I hope that didn't break anything, I never did a squash before.

I've followed [this guide](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) to combine these commits into one. In the process I removed the Snap commit to keep things tidy (and also because it looks like that's already merged upstream).

Let me know if there's anything else I should do.

**Comment by mgumz** [comment]
ok, i cherry-picked 0c3729a, now i am ready for the rest of it .) can you please rebase?

**Comment by Nephiel** [comment]
Sorry, I screwed up on my repo and had to fork master anew. Will open a new pull request.

**Comment by Nephiel** [comment]
Done. I opened a new, clean, pull request: [https://github.com/fluxbox/fluxbox/pull/23]

**Pull request closed without merging**
