### PR TITLE
Layerfix

### PR DESCRIPTION
**Pull request by gregor-b**
This makes fluxbox much more usable than these pseudo-desktops do, also it's the default behaviour of other common window managers like openbox.

See also https://sourceforge.net/p/fluxbox/patches/170/
(the "briefly tested" is now "tested for a month in everyday use")

### CODE REVIEW

**Comment by mgumz** [comment]
so, whats the state of this now?

**Comment by gregor-b** [comment]
I rebased my changes on r137 but this doesn't affect the layerfix-patch. The current version under https://github.com/gregor-b/fluxbox/tree/layerfix is still the same as in the pull request.

Best regards.

**Comment by mgumz** [comment]
what if the layer of the transient window IS actually the DESKTOP-layer 

```
     if (twin && twin != this) {
-        layerItem().setLayer(twin->layerItem().getLayer());
-        m_state.layernum = twin->layerNum();
+        if (twin->layerNum() != ::ResourceLayer::DESKTOP) {
+            layerItem().setLayer(twin->layerItem().getLayer());
+            m_state.layernum = twin->layerNum();
+        }
         m_workspace_number = twin->workspaceNumber();
     } else // if no parent then set default layer
         moveToLayer(m_state.layernum, m_state.layernum != ::ResourceLayer::NORMAL);
```

isn't your PR to "enforce" that transient windows are at least +1 above the DESKTOP layer?

**Comment by sporkbox** [comment]
@gregor-b Actually, the primary maintainer of Fluxbox is @mgumz and he generally responds to most things, both here and on SF. The fastest way to reach him is via IRC. `#fluxbox` on Freenode.

**Pull request closed without merging**
